# ref

## preamble

```{r load-deps, message=FALSE, warning=FALSE}
library(qs)
library(Seurat)
library(scuttle)
library(patchwork)
library(SingleCellExperiment)
source("code/_utils.R")
```

## loading

```{r load-data, warning=FALSE}
qs <- list.files("data/ref", "qs$", full.names=TRUE)
names(qs) <- gsub("\\.qs", "", basename(qs))
se <- lapply(qs, \(.) {
    so <- qread(.)
    se <- as.SingleCellExperiment(so)
    logcounts(se) <- NULL
    dr <- tail(reducedDims(se), 1)[[1]]
    reducedDims(se) <- list(UMAP=dr)
    gs <- VariableFeatures(so)
    gs <- rownames(se) %in% gs
    rowData(se)$hvg <- gs
    se
}); sapply(se, dim)
```

## labeling

### nkt

```{r nkt, results="hold"}
old <- c("0","1","2","3","4","5","6","7","8","9","11","12","13","14","15","17","18")
nev <- c(
    "CD16pos NK","CD4 TCM TFH","TEMRA","CD4 TN","CD8 TPEX","CD4 TREG",
    "CD4 TCM TH2","NK-like T","NK ILC3","CD8 TEX","CD4 TCM","CD8 TEM",
    "CD16neg NK","CD8 TN","MAIT","Cycling T","IFN responding")
new <- list(
    NK=c("CD16neg NK", "CD16pos NK", "NK ILC3"),
    Tfh="CD4 TCM TFH", Treg="CD4 TREG",
    Tcm=c("CD4 TCM TH2", "CD4 TCM"),
    Tex=c("CD8 TPEX", "CD8 TEX"), 
    Thn="CD4 TN", Tcn="CD8 TN",
    Tem="CD8 TEM")
new <- setNames(rep.int(names(new), sapply(new, length)), unlist(new))
lap <- se$nkt$lap <- nev[match(se$nkt$ident, old)]
lab <- se$nkt$lab <- new[match(lap, names(new))]
table(lab, exclude=NULL)
table(lap[is.na(lab)])
```

### mye

```{r mye, results="hold"}
old <- c("0","1","2","3","4","5","6","7","8","9","10","11")
nev <- c(
    "Classical_monocytes", "Class. monocytes_HLA", 
    "Non-class. monocytes", "Class. monocytes_SELL", 
    "Class. monocytes_ribo", "DC2", "Class. monocytes_IFNresp", 
    "pDC_1", "Progenitor cells", "Platelets", "pDC_2", "DC1")
new <- list(
    mono.c=c(
        "Classical_monocytes",
        "Class. monocytes_HLA",
        "Class. monocytes_ribo",
        "Class. monocytes_SELL",
        "Class. monocytes_IFNresp"),
    mono.nc="Non-class. monocytes",
    pDC=c("pDC_2", "pDC_1"),
    DC=c("DC1", "DC2"))
new <- setNames(rep.int(names(new), sapply(new, length)), unlist(new))
lap <- se$mye$lap <- nev[match(se$mye$ident, old)]
lab <- se$mye$lab <- new[match(lap, names(new))]
table(lab, exclude=NULL)
table(lap[is.na(lab)])
```

### tum

```{r tum, results="hold"}
old <- c("0","1","2","3","4","5","6","7","8","9")
nev <- c(
    "Quiescent", "SOX11 network", "Immediate-early response",
    "Memory/nnMCL", "Reactivated memory B cell", "Pre/Pro B cell",
    "MYC pathway", "BCR signaling/NFKB pathway", "S-Phase", "G2/M")
new <- list(
    tum.low=c(
        "Quiescent", "Immediate-early response", "Memory/nnMCL", 
        "Reactivated memory B cell", "Pre/Pro B cell"),
    tum.act=c("SOX11 network", "MYC pathway", "BCR signaling/NFKB pathway"),
    tum.pro=c("S-Phase", "G2/M"))
new <- list(
    tum.qui="Quiescent",
    tum.low=c(
        "Immediate-early response", "Memory/nnMCL", 
        "Reactivated memory B cell", "Pre/Pro B cell"),
    tum.myc="MYC pathway",
    tum.sox="SOX11 network",
    tum.bcr="BCR signaling/NFKB pathway",
    tum.pro=c("S-Phase", "G2/M")
)
new <- setNames(rep.int(names(new), sapply(new, length)), unlist(new))
lap <- se$tum$lap <- nev[match(se$tum$seurat_clusters, old)]
lab <- se$tum$lab <- new[match(lap, names(new))]
table(lab, exclude=NULL)
table(lap[is.na(lab)])
```

```{r plt, fig.width=10, fig.height=4}
#| code-fold: true
wrap_plots(nrow=1, lapply(se, \(x) wrap_plots(lapply(c("lap", "lab"), \(y) .plt_dr(x, y)), ncol=1))) &
    guides(col=guide_legend(NULL, override.aes=list(size=1.5))) &
    theme(legend.justification=c(0, 0.5))
```

## pooling

```{r pool}
gs <- Reduce(intersect, lapply(se, rownames))
mx <- do.call(cbind, lapply(se, \(.) assay(.)[gs, ]))
dim(mx <- normalizeCounts(mx, log=FALSE))
```

## profiles

### low-res.

```{r pbs-one}
id <- rep.int(names(se), sapply(se, ncol))
id[unlist(lapply(se, \(.) is.na(.$lab)))] <- NA
pb <- summarizeAssayByGroup(mx, id, statistics="mean")
head(pb <- assay(pb))
```

### high-res.

```{r pbs-two}
qb <- lapply(se, \(.) {
    if (is.null(id <- .$lab)) return()
    cs <- colnames(.)[!(ex <- is.na(id))]
    summarizeAssayByGroup(mx[, cs], id[!ex], statistics="mean")
})
qb <- qb[!sapply(qb, is.null)]
qb <- lapply(qb, assay)
sapply(qb, colnames)
```

## appendix

### saving

```{r save-data}
saveRDS(pb, "outs/pbs.rds")
saveRDS(qb, "outs/qbs.rds")
```

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
#| code-fold: false
sessionInfo()
```

:::