# ccc

## preamble

```{r load-deps, message=FALSE, warning=FALSE}
library(RANN)
library(Matrix)
library(scater)
library(reticulate)
library(BiocParallel)
library(zellkonverter)
library(SingleCellExperiment)
source("code/_utils.R")
bp <- MulticoreParam(6)
# activate conda environment
bin <- "~/software/mambaforge/bin"
use_python(file.path(bin, "python"))
use_condaenv("commot", file.path(bin, "conda"))
```

## loading

```{r load-data}
sce <- readRDS("outs/fil.rds")
(sce <- logNormCounts(sce))
```

## analysis

### radius

```{r nns-get, fig.width=7, fig.height=3.5}
# get radial nearest neighbors
xy <- grep("global_mm$", names(colData(sce)))
xy <- as.matrix(colData(sce)[xy])
reducedDim(sce, "spatial") <- xy
nn <- nn2(xy, searchtype="radius", r=r <- 0.02, k=101)
```

```{r nns-plt, fig.width=7, fig.height=3.5}
#| code-fold: true
n <- rowSums(nn$nn.idx[, -1] > 0)
l <- sprintf("#cells in %sum radial neighborhood", r*1e3)
hist(n, breaks=seq(-.5, max(n)+.5), xlab="", ylab="",  main=l)
abline(v=quantile(n, c(.05, .95)), col="red", lw=2, lty=2)
abline(v=m <- mean(n), col="red", lw=2); m
```

### setup

```{r ccc-set}
# dependencies
ad <- import("anndata")
ct <- import("commot")
pd <- import("pandas")

# retrieve interactions from 'CellChatDB'
db <- ct$pp$ligand_receptor_database(
    species="human", 
    database="CellChat", 
    signaling_type=NULL)
names(db) <- c(
    "ligand", "receptor", 
    "pathway", "type")
nrow(db)

# filter for interactions
# fully covered by panel
db <- db[apply(db, 1, \(.) {
    rs <- strsplit(.["receptor"], "_")
    lr <- c(.["ligand"], unlist(rs))
    all(lr %in% rownames(sce))
}), ]
nrow(db)

# subset to features being considered
rs <- sapply(strsplit(db$receptor, "_"), .subset, 1)
nrow(sub <- sce[unique(c(db$ligand, rs)), ])
```

### inference

```{r ccc-run}
set.seed(260204)
bo <- bpoptions(progressbar=TRUE)
cs <- split(colnames(sce), sce$sid)
sr <- bplapply(
    BPPARAM=bp, BPOPTIONS=bo, 
    names(cs), \(f) {
        tryCatch(error=\(e) e, {
            ad <- SCE2AnnData(
                sce=sub[, cs[[f]]], 
                X_name="logcounts")
            ct$tl$spatial_communication(ad,
                dis_thr=0.02,  
                df_ligrec=db,
                heteromeric=TRUE,
                pathway_sum=TRUE,
                database_name="foo",
                heteromeric_rule="min",
                heteromeric_delimiter="_")
            list(
                ad$obsm["commot-foo-sum-sender"], 
                ad$obsm["commot-foo-sum-receiver"])
        })
    })
er <- sapply(sr, inherits, "error")
ex <- sapply(sr, is.null)
sr <- sr[!(er|ex)]
```

### wrangling

```{r post}
# collect
s <- lapply(sr, \(.) .[[1]])
r <- lapply(sr, \(.) .[[2]])
s <- do.call(rbind, unname(s))
r <- do.call(rbind, unname(r))
lys <- list(s=s, r=r)
res <- lapply(lys, \(.) {
    mtx <- as(as.matrix(.), "dgCMatrix")
    nms <- gsub("^(s|r)-", "", colnames(.))
    `colnames<-`(mtx[colnames(sce), ], nms)
})

# metadata
lr <- with(db, paste(ligand, receptor, sep="-"))
is <- match(nm <- colnames(res[[1]]), lr)
dp <- `rownames<-`(db[is, ], nm)
tt <- grep("total", nm)
dp$type[tt] <- "Total"
na <- is.na(dp$type)
dp$type[na] <- "Pathway"
dp$pathway[na] <- nm[na]

# reformat
res <- SingleCellExperiment(
    assays=lapply(res, t), 
    colData=colData(sce), 
    rowData=dp); res
```

## appendix

### saving

```{r save-data}
saveRDS(res, "outs/ccc.rds")
```

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
#| code-fold: false
sessionInfo()
```

:::