# clu

## preamble

```{r load-deps, message=FALSE, warning=FALSE}
library(scran)
library(scater)
library(igraph)
library(scuttle)
library(isotree)
library(pheatmap)
library(BiocParallel)
library(SingleCellExperiment)
source("code/_utils.R")
bp <- MulticoreParam(4)
set.seed(260216)
```

## loading

```{r load-data}
(sce <- readRDS("outs/pro.rds"))
```

## filtering

```{r results="hold", fig.width=8, fig.height=3}
# matrix of signaling estimates
scf <- altExp(sce, "COMMOT")

# feature restriction
t(t(table((rd <- rowData(scf))$type)))
table(sel <- !rd$type %in% c("Pathway", "Total"))

ol <- lapply(assayNames(scf), \(a) {
    x <- assay(scf, a)["total-total", ]
    x <- isOutlier(x, 5, type="lower", log=TRUE)
}) 
par(mfrow=c(1, 2))
for (. in c(1, 2)) {
    x <- assay(scf, .)["total-total", ]
    hist(log2(x), main=assayNames(scf)[.], n=100)
    abline(v=attr(ol[[.]], "threshold")[1], col="red")
}
ol <- do.call(cbind, ol)
scf <- scf[, !rowAnys(ol)]
sce <- sce[, colnames(scf)]
```

## analysis

```{r}
lrs <- rowData(scf)[sel, c("ligand", "receptor")]
lrs <- unique(unlist(strsplit(unlist(lrs), "_")))
sce <- runPCA(sce, subset_row=lrs, ncomponents=30)
sce <- runUMAP(sce, dimred="PCA", metric="cosine", BPPARAM=bp)
```

```{r fig.width=5, fig.height=3}
par(mar=c(4,4,0,0))
pcs <- reducedDim(sce, "PCA")
pve <- attr(pcs, "percentVar")
npc <- PCAtools::findElbowPoint(pve)
plot(pve, xlab="PC", ylab="PVE", type="l")
points(pve, col="blue", cex=0.8)
abline(v=npc, col="red", lwd=2)
```

```{r iso, message=FALSE, fig.width=12, fig.height=3}
mod <- isolation.forest(pcs, ndim=10, ntrees=100, nthreads=1)
sce$sco <- predict(mod, pcs, type="score")
sce$out <- (ol <- isOutlier(sce$sco, 3, type="higher"))
```

```{r fig.width=6, fig.height=3}
par(mar=c(4,4,0,0))
hist(sce$sco, n=100, main="")
th <- attr(ol, "threshold")[2]
abline(v=th, col="red")
```

```{r message=FALSE, results="hold", fig.width=5, fig.height=3}
table(sce$out <- sce$sco > th)
.plt_dr(sce, "sco") +
.plt_dr(sce[, order(sce$out)], "out") + 
scale_color_manual(values=c("lavender", "blue"))
```

```{r}
sce <- sce[, !sce$out]
scf <- scf[, colnames(sce)]
```

```{r}
sce <- harmony::RunHarmony(sce, "pid", verbose=FALSE)
sce <- runUMAP(sce, dimred="HARMONY", metric="cosine", BPPARAM=bp)
```

```{r}
g <- buildSNNGraph(sce, type="jaccard", use.dimred="PCA", k=10)
k <- cluster_leiden(g, objective_function="modularity", resolution=5)
ks <- seq_along(unique(k <- k$membership))
nlevels(sce$clu <- factor(k, ks))
```

```{r plt-dr, fig.width=5, fig.height=3}
sce$foo <- as.integer(sce$clu); .plt_dr(sce, "foo") + 
.plt_dr(sce, "lv1") + scale_color_manual(values=.pal_sub)
```

```{r message=FALSE, fig.width=18, fig.height=3}
.plt_fq(sce, "clu", "lv1") + 
    scale_fill_manual(NULL, values=.pal_sub) +
.plt_fq(sce, "clu", "lv2") + 
    scale_fill_manual(NULL, values=.pal_kid) +
.plt_fq(sce[, sce$lv1 != "tum"], "clu", "lv2") + 
    scale_fill_manual(NULL, values=.pal_kid) +
plot_layout(nrow=1) &
    theme(axis.text.x=element_blank()) 
```

```{r mu}
names(as) <- as <- c("s", "r")
mu <- lapply(as, \(a) {
    se <- `assays<-`(scf, value=list(logcounts=assay(scf, a)))
    ks <- sce$clu[match(colnames(se), colnames(sce))]
    aggregateAcrossCells(se, ks, 
        use.assay.type="logcounts", 
        statistics="mean")
})
```

<!--

```{r e2g, fig.width=4, fig.height=2, eval=FALSE}
# par(mar=c(4,4,0,0))
# s <- assay(mu[[1]])[sel, ]
# r <- assay(mu[[2]])[sel, ]
# cm <- t(s) %*% r
# e <- data.frame(
#     w=c(cm),
#     i=rownames(cm)[c(row(cm))],
#     j=colnames(cm)[c(col(cm))])
# hist(e$w, n=100, main="")
# abline(v=th <- quantile(e$w, 2/3), col="red")
```

```{r eval=FALSE}
# # build graph from cell-cell interaction matrix
# f <- as.matrix(e[, c("i","j")])
# g <- graph_from_edgelist(f, FALSE)
# w <- e$w; w[w < 0] <- 0
# edge_attr(g, "weight") <- w
# g <- delete_edges(g, E(g)[e$w < 2/3])
# table(ex <- degree(g) == 0)
# #plot(g, layout=layout_with_mds)
# g <- delete_vertices(g, V(g)[ex])
# k <- cluster_leiden(g, objective_function="CPM", resolution=0.5)
# k <- k$membership; k <- factor(k, seq_along(unique(k))); table(k)
```

-->

```{r sco-mtx}
cm <- t(s) %*% r
clu <- hclust(dm <- dist(cm))
opk <- maptree::kgs(clu, dm, 0.5, 20)
k <- opk[which.min(opk)]
k <- as.integer(names(k))
k <- factor(cutree(clu, 15))
```

```{r plt-cm, fig.width=6, fig.height=6.5}
#| code-fold: true
df <- data.frame(k)
o <- order(as.integer(k))
mc <- cm[o, ]; mc <- mc[, o]
pal <- rep(pals::polychrome(), 2)
pal <- setNames(pal, unique(k))
pal <- pal[seq_along(unique(k))]
qs <- quantile(cm, c(0.01, 0.99))
pheatmap(mc,
    fontsize=6,
    border_color=NA,
    cellwidth=3, cellheight=3,
    treeheight_row=6, treeheight_col=6,
    breaks=seq(qs[1], qs[2], l=n <- 100),
    color=hcl.colors(n-1, "Batlow"),
    #color=rev(pals::brewer.rdbu(n-1)),
    show_rownames=FALSE, show_colnames=FALSE,
    cluster_rows=FALSE, cluster_cols=FALSE,
    #cluster_rows=TRUE, cluster_cols=TRUE,
    annotation_row=df, annotation_col=df,
    annotation_colors=list(k=pal),
    gaps_row=cumsum(table(k)), 
    gaps_col=cumsum(table(k)))
```

```{r fig.width=7, fig.height=6.5}
# filter low-scoring clusters 
avg <- sapply(levels(k), \(.) {
    x <- cm[k == ., , drop=FALSE]
    x <- x[, k == .]
    mean(x, na.rm=TRUE)
})
avg[is.na(avg)] <- -Inf
(ex <- which(avg < median(cm)))
k[k %in% ex] <- NA
ks <- seq_along(setdiff(unique(k), NA))
table(k <- factor(k, labels=ks))
```

```{r}
# propagate bulk labels to cells
vs <- vertex_attr(g, "name")
vs <- rownames(cm)
cs <- split(colnames(sce), sce$clu)
is <- match(colnames(sce), unlist(cs[vs]))
ks <- rep.int(k, sapply(cs, length)[vs])[is]
ks[ks %in% names(which(table(ks) < 100))] <- NA
ks <- factor(ks, seq_along(setdiff(unique(ks), NA)))
table(scf$ccc <- ks, useNA="ifany")
table(scf$ccc, scf$lv1)
```

```{r}
round(sapply(assayNames(scf), \(a) by(assay(scf, a)["total-total", ], scf$ccc, mean)), 2)
```

## visuals

### composition

::: {.panel-tabset}

```{r plt-fq, results="asis", message=FALSE, fig.width=5, fig.height=3}
#| code-fold: true
pal <- rep(unname(pals::polychrome()), 2)
ys <- list(
    pid=.pal_pid, sid=.pal_sid, 
    lv1=.pal_sub, lv2=.pal_kid, 
    cty=.pal_ctx)
ps <- lapply(setNames(names(ys), names(ys)), \(.) {
    cs <- if (. == "lv2") which(scf$lv2 != "tum") else TRUE
    scf[[.]] <- as.character(scf[[.]])
    ps <- list(
        .plt_fq(scf[, cs], "ccc", .) + scale_fill_manual(values=ys[[.]]),
        .plt_fq(scf[, cs], ., "ccc") + scale_fill_manual(values=pal))
    wrap_plots(ps) & coord_equal(20, expand=FALSE)
})
for (. in names(ps)) {cat("####", ., "\n"); print(ps[[.]]); cat("\n\n")}
```

:::

### expression

::: {.panel-tabset}

```{r plt-de, results="asis", fig.width=9, fig.height=12}
xs <- list(LR=sel, PW=rd$type == "Pathway")
for (. in names(xs)) {
    ps <- lapply(c("s", "r"), \(a) {
        se <- scf[xs[[.]], ]
        gs <- findMarkers(se, se$ccc,
            assay.type=a, direction="up",
            add.summary=TRUE, BPPARAM=bp)
        gs <- lapply(gs, \(df) head(rownames(df), 15))
        mu <- aggregateAcrossCells(
            se[unique(unlist(gs)), ], se$ccc,
            use.assay.type=a, statistics="mean")
        pal <- rev(pals::brewer.rdbu(n <- 99))
        hm <- plotHeatmap(mu, 
            features=rownames(mu), 
            border_color=NA, color=pal,
            silent=TRUE, show_colnames=TRUE,
            treeheight_row=9, treeheight_col=9,
            fontsize=9, cellwidth=9, cellheight=9,
            exprs_values=a, center=TRUE, scale=TRUE,
            legend_breaks=seq(-2.5, 2.5, l=n),
            legend_labels=rep("", n))
        ggplotify::as.ggplot(hm)
    })
    cat("####", ., "\n"); print(wrap_plots(ps, nrow=1)); cat("\n\n")
}
```

:::

### spatial

::: {.panel-tabset}

```{r plt-xy, results="asis", fig.dpi=100, message=FALSE, fig.width=10, fig.height=3}
idx <- split(colnames(scf), scf$sid)
pol <- arrow::read_parquet("outs/pol.parquet", as_data_frame=FALSE)
pal <- list(lv1=.pal_sub, ccc=rep(unname(pals::polychrome()[-2]), 2))
pal <- lapply(pal, \(.) scale_fill_manual(drop=FALSE, na.value="lightgrey", values=.))
for (i in c("122LNm", "011LNd", "061LNd")) { # couple structurally interesting cores
    se <- scf[, idx[[i]]]
    for (. in names(pal)) se[[.]] <- factor(se[[.]])
    ps <- lapply(names(pal), \(j) {
        id <- if (j == names(pal)[2]) i
        .plt_ps(pol, se, j, id=id, lw=0.1, lc="white") + pal[[j]]
    })
    gg <- wrap_plots(ps, nrow=1) & theme(plot.margin=margin(r=5))
    cat("####", i, "\n"); print(gg); cat("\n\n")
}
```

:::

<!--

## labeling

```{r lab, eval=FALSE}
lab <- list(
    "BEC"=c(7),
    "CAF"=c(5),
    "EPI"=c(15),
    "CD99"=c(3,11),
    "MHC-II/CD4"=c(1),
    "cytotoxicity"=c(6,13,16),
    "stromal"=c(2,12),
    "CXCL13"=c(8),
    "exhaustion"=c(14),
    "APP/CD74"=c(10),
    "tumor"=c(4,9,17,18)
); any(duplicated(unlist(lab)))
lap <- rep.int(names(lab), sapply(lab, length))
lap <- setNames(unlist(lab), lap)
tmp$.ccc <- tmp$ccc # keep raw assignments
tmp$ccc <- names(lap)[match(tmp$ccc, lap)]
table(tmp$.ccc, tmp$ccc)
```

-->
