# eda

## preamble

### setup

```{r dirs, message=FALSE, warning=FALSE}
source("_utils.R")
DIR <- dirname(getwd())
OUT <- file.path(DIR, "outs")
```

### deps

```{r deps, message=FALSE, warning=FALSE}
library(arrow)
library(scran)
library(scater)
library(scuttle)
library(tidytext)
library(BiocParallel)
library(SingleCellExperiment)
bp <- MulticoreParam(4)
set.seed(251206)
```

### loading

```{r load-data}
(sce <- readRDS(file.path(OUT, "pro.rds")))
sig <- readRDS(file.path(OUT, "sig.rds"))
colData(sig) <- colData(sce)
altExp(sce, "UCell") <- sig
```

## reduction

```{r plt-dr-one, fig.width=6, fig.height=5}
#| code-fold: true
.plt_dr(sce, "pid") + scale_color_manual(values=.pal_pid) +
.plt_dr(sce, "gid") + scale_color_manual(values=.pal_gid) +
.plt_dr(sce, "typ") + scale_color_manual(values=.pal_typ) +
.plt_dr(sce, "lv1") + scale_color_manual(values=.pal_sub) +
    plot_layout(nrow=2) & theme(
        aspect.ratio=1,
        plot.margin=margin(l=5, b=5),
        legend.justification=c(0, 0.5))
```

```{r plt-dr-two, fig.width=8, fig.height=2.5}
#| code-fold: true
cs <- split(colnames(sce), sce$lv1)
cs <- cs[setdiff(names(cs), "tum")]
ps <- lapply(names(cs), \(.) {
    sub <- sce[, cs[[.]]]
    .plt_dr(sub, "lv2", dr="UMAQ", s=0.4, id=.) +
    scale_color_manual(values=unname(pals::trubetskoy()))
})
wrap_plots(ps, nrow=1) & theme(
    aspect.ratio=1,
    plot.margin=margin(l=5, b=5),
    legend.justification=c(0, 0.5))
```

## marker

```{r echo=FALSE}
.plt_dp <- \(sce, id, gs) {
    gs <- lapply(gs, intersect, rownames(sce))
    ns <- sapply(gs, length)
    gt <- unlist(gs)
    mu <- summaryMarkerStats(sce[gt, ], sce[[id]])
    mu <- lapply(mu, \(.) data.frame(g=rownames(.), .))
    mu <- mu |>
        bind_rows(.id="k") |>
        group_by(g) |>
        mutate_at("self.average", .z) |>
        mutate_at("g", factor, gt) |>
        mutate_at("k", factor, rev(names(gs)))
    s <- cumsum(ns)
    n <- length(ns)
    bb <- 0.5+data.frame(
        xmin=rev(c(0,s[-n])), xmax=rev(s),
        ymin=seq(n), ymax=c(0,seq(n)[-n]))
    ggplot(mu, aes(g, k, col=self.average, size=self.detected)) + geom_point() +
        geom_rect(inherit.aes=FALSE, fill=NA, col="black", linewidth=0.4,
            aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), bb) +
        scale_color_gradient2(low="blue3", mid="grey95", high="red3") +
        scale_size_continuous(breaks=seq(0, 1, .2), range=c(1, 5)) +
        guides(col=guide_colorbar(order=1)) +
        coord_equal() + 
        .thm_fig_c("minimal") + theme(
            panel.grid=element_blank(),
            axis.title=element_blank(),
            axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
}
```

::: {.panel-tabset}

### nkt

```{r fig.width=9, fig.height=3}
gs <- list(
    Tha=c("TRBC1", "TRBC2", "CD2", "CD3D", "CD3E", "CD3G", "STAT4","CD4"),
    Thn=c("CD6"),
    Tcm=c("KLF2", "TUBB2A", "TUBB2B"),
    Tfh=c("ICOS", "BCL6", "CXCL13", "CD40LG"),
    Tcn=c("CD8A", "CD8B", "CCR7", "CD28", "CD44", "CD200A"),
    Treg=c("TNFRSF4", "IL2RA", "FOXP3", "CTLA4"),
    Tex=c("KLRG1", "TIGIT", "HAVCR2", "LAG3", "PDCD1", "VCAM1", 
        "TNFRSF9", "TNFRSF18", "IFNG", "CXCR6", "GLNY", "DUSP4", "TOX"),
    Tp=c("MKI67", "TOP2A", "TUBB4A", "TUBB4B", 
        "CX3CR1", "CDK6", "GZMA", "GZMB", "GZMH", "GZMK", "EOMES"),
    NK=c("ENTPD1", "NKG7", "PRF1", "TBX21", "KLRB1", "KLRC3", "IL2RB", "CD7")
)
sub <- sce[, sce$lv1 == "nkt"]
.plt_dp(sub, "lv2", gs)
```

### mye

```{r fig.width=9, fig.height=3}
gs <- list(
    AML=c(),
    mye=c(),  
    DC=c("CLEC9A", "CLEC10A", "LAMP3", "IDO1", "XCR1",
        "HLA-DPA1", "HLA-DPB1", "HLA-DQB1"),
    pDC=c("IRF8", "IRF7", "CR2", "FCRL2", "FCRL5", "CLEC4C"),
    moDC=c("SELENOP", "CD14", "CD163", "C1QA", "C1QB", "C1QC", "CTSB"),
    mono.nc=c("FCER1G", "B2M", "AIF1", "BLVRB"),
    mono.c=c("FBP1", "PCK2", "LYZ"),
    mac.pi=c("CD68", "APOE", "MMP9", "MMP12", "MMP14", "ITGAX")
)
sub <- sce[, sce$lv1 == "mye"]
.plt_dp(sub, "lv2", gs)
```

### str

```{r fig.width=9, fig.height=3}
gs <- list(
    fib=c(
        "COL1A1", "COL1A2", "COL3A1", "COL6A3", "COL5A1", "COL5A2", "COL5A3", 
        "COL14A1", "CXCL10", "ACTA2", "PDGFRA", "PDGFRB", "FN1"),
    mCAF=c("DCN", "COL12A1", "MMP1", "MMP2", "IGF2", "POSTN", "MYL9", "IGFBP5"),
    FRCcts=c("CCN1", "JUNB", "JUN", "FOS", "FOSB", "CCL2", "EGR1", "EGR3", "GBP1"),
    FRCtcz=c("CCL19", "CCL21", "CXCL12", "VCAM1", "COL27A1", "FDCSP", "CLU", "CR2", "CXCL13"),
    FRCpv=c("NOTCH3", "NOTCH4", "COL18A1", "COL4A1", "HEY1", "DLL4", "CAV1", "LAMA4", "LMNA"),
    BEC=c("FLT1", "CLEC14A", "CDH5", "CD34", "CD93", "VWF"),
    LEC=c("MYO6", "SRGN", "LYVE1", "PROX1", "CXCL1", "CXCL2"),
    epi=c("KRT5", "KRT7", "KRT14", "KRT16", "KRT17", "KRT19")
)
sub <- sce[, sce$lv1 == "str"]
.plt_dp(sub, "lv2", gs)
```

:::

## signatures

```{r sig}
sig <- altExp(sce, "UCell")
```

```{r echo=FALSE}
.plt_cor <- \(se) {
    pal <- c("turquoise", "ivory", "deeppink")
    pal <- colorRampPalette(pal)(99)
    pheatmap::pheatmap(cor(t(assay(se))),
        main="inter-signature correlation",
        cellwidth=10, cellheight=10,
        treeheight_row=20, treeheight_col=20, 
        fontsize=9, color=pal, border_color=NA)
}
.plt_avg <- \(se, by) {
    df <- data.frame(t(assay(se)), colData(se), check.names=FALSE)
    fd <- pivot_longer(df, all_of(rownames(se)))
    mu <- fd |>
        group_by(name, !!sym(by)) |>
        summarise_at("value", mean) |>
        group_by(name) |>
        mutate_at("value", .z)
    mx <- pivot_wider(mu)
    my <- as.matrix(mx[, -1])
    rownames(my) <- mx[[1]]
    ggplot(mu, aes(.data[[by]], name, fill=value)) + geom_tile() +
        scale_fill_gradient2(
            "z-scaled\nmean UCell", 
            limits=c(-2.5, 2.5), breaks=seq(-2, 2, 2),
            low="turquoise", mid="ivory", high="deeppink") +
        scale_x_discrete(limits=.xo(my)) +
        scale_y_discrete(limits=.yo(my)) +
        coord_equal(expand=FALSE) +
        .thm_fig_c("minimal") + theme(
            axis.title=element_blank(),
            axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
}
```

### nkt

```{r sig-nkt}
.sig <- sig[rowData(sig)$typ == "t-atlas", sig$lv1 == "nkt"]
```

```{r sig-nkt-cor, fig.width=10, fig.height=8}
#| code-fold: true
.plt_cor(.sig)
```

```{r fig.width=10, fig.height=4}
#| code-fold: true
.plt_avg(.sig, "sid") + 
.plt_avg(.sig, "lv2") + 
.plt_avg(.sig, "ctx") + 
plot_layout(guides="collect")
```

### tum

```{r sig-tum}
.sig <- sig[rowData(sig)$typ != "t-atlas", sig$lv1 == "tum"]
```

```{r sig-tum-cor, fig.width=10, fig.height=8}
#| code-fold: true
.plt_cor(.sig)
```

```{r sig-tum-box, fig.width=12, fig.height=4}
#| code-fold: true
.plt_avg(.sig, "sid") + 
.plt_avg(.sig, "ctx") + 
plot_layout(guides="collect")
```

```{r echo=FALSE, eval=FALSE, fig.width=5, fig.height=4}
sub <- sce[, sce$lv1 == "tum"]
sub$foo <- sub$fqs[, "tum"]
ids <- colData(sub)[c("sid", "ctx")]
pbs <- aggregateAcrossCells(sub, ids, coldata.merge=list(foo=mean))
pbs <- logNormCounts(`sizeFactors<-`(pbs, value=NULL))
pbs <- runPCA(pbs, ncomponents=5, subset_row=rowData(pbs)$tum)
plotPCA(pbs, colour_by="foo") + coord_equal()
```

## appendix

### save data

```{r save-data}

```

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
#| code-fold: false
sessionInfo()
```

:::