# eda

## preamble

```{r load-deps, message=FALSE, warning=FALSE}
library(arrow)
library(scran)
library(scater)
library(scuttle)
library(pheatmap)
library(BiocParallel)
library(SingleCellExperiment)
source("code/_utils.R")
bp <- MulticoreParam(4)
set.seed(260205)
```

## loading

```{r load-data}
(sce <- readRDS("outs/pro.rds"))
```

## stats

```{r Tex-ctx}
#| code-fold: true
fq <- prop.table(table(sce$lv2, sce$cty), 1)
df <- filter(data.frame(fq), Var1 == "Tex")
(gg <- ggplot(df, aes(reorder(Var2, Freq), Freq, fill=Var2)) + 
    scale_x_discrete(expand=expansion(0, 1)) +
    scale_y_continuous(expand=expansion(0.04), limits=c(0, 0.6), breaks=seq(0, 1, 0.2)) +
    geom_text(aes(label=Var2), angle=90, hjust=-0.2, size=0.8) +
    geom_col(width=1, col="black", linewidth=0.05, key_glyph="point") +
    scale_fill_manual(NULL, values=.pal_ctx) +
    labs(x=NULL, y="Tex fraction") +
    .thm_fig_d("classic", "f") + theme(
        aspect.ratio=3/2,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.minor=element_blank()))
```

```{r include=FALSE}
ggsave("figs/Tex_by_ctx.pdf", gg, units="cm", width=2.5, height=3)
```

```{r fig.width=4, fig.height=2.5}
#| code-fold: true
gs <- c("CCND1", "TUBB", "MYC", "SOX11", "TOP2A", "MKI67", "CDK1")
fq <- as.matrix(counts(sce[gs, ]) > 0)
df <- data.frame(colData(sce), t(fq))
df <- df[which(df$lv1 == "tum"), ]
fd <- df |>
    group_by(sid) |>
    summarize(across(all_of(gs), mean)) |>
    pivot_longer(all_of(gs)) |>
    mutate_at("name", factor, rev(gs))
mx <- pivot_wider(fd)
my <- as.matrix(mx[, -1])
rownames(my) <- mx[[1]]
# xy <- list(
#     scale_x_discrete(limits=.xo(my)),
#     scale_y_discrete(limits=.yo(my)))
(gg <- ggplot(fd, aes(sid, name, fill=value)) + geom_tile() +
    scale_x_discrete(limits=names(sort(my[, "CCND1"]))) +
    scale_fill_gradientn(NULL, colors=.pal_bow, limits=c(0, 1), n.breaks=2) +
    coord_equal(expand=FALSE) +
    .thm_fig_c("bw") + theme(
        panel.grid=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank(),
        axis.text.y=element_text(size=4),
        axis.text.x=element_text(size=4, angle=45, hjust=1)))
```

```{r fig.width=4, fig.height=2.5}
ggsave("figs/gs,hm.pdf", gg, units="cm", width=5, height=2.5)
```

## reduction

```{r plt-map, message=FALSE, fig.width=6, fig.height=5}
#| code-fold: true
.plt_dr(sce, "pid") + scale_color_manual(values=.pal_pid) +
.plt_dr(sce, "gid") + scale_color_manual(values=.pal_gid) +
.plt_dr(sce, "typ") + scale_color_manual(values=.pal_typ) +
.plt_dr(sce, "lv1") + scale_color_manual(values=.pal_sub) +
    plot_layout(nrow=2) & theme(
        aspect.ratio=1,
        plot.margin=margin(l=5, b=5),
        legend.justification=c(0, 0.5))
```

## tumor

```{r}
sub <- sce[, which(sce$lv1 == "tum")]
mtx <- counts(sub)[c("CCND1", "SOX11"), ] > 0
c(rowMeans(mtx), both=mean(colAlls(mtx)))
```

## signatures

```{r sig}
sig <- altExp(sce, "UCell")
sig <- sig[rowData(sig)$typ != "t-atlas", ]

# simplify signature identifiers
nms <- rownames(sig)
rnm <- c(
    HALLMARK="HM", 
    TGF_BETA="TGFB",
    INTERFERON_ALPHA="IFNA",
    INTERFERON_GAMMA="IFNG",
    GAVISH_3CA_METAPROGRAM_B_CELLS="MP")
for (. in seq_along(rnm))
    nms <- gsub(names(rnm)[.], rnm[.], nms)
rownames(sig) <- nms
sig
```

```{r fig.width=15, fig.height=12}
#| code-fold: true
mx <- UpSetR::fromList(rowData(sig)$set)
UpSetR::upset(mx, nintersects=50, nsets=nrow(sig)/2, mb.ratio=c(0.4, 0.6))
```

```{r plt-sig-xy, results="hide", message=FALSE, echo=FALSE, eval=FALSE}
ys <- .smooth_xy(sig, a=1, r=0.01, k=51)
ys <- apply(ys, 1, \(.) {
    .[sce$lv2 != "tum"] <- NA
    return(.z(.))
})
cs <- split(colnames(sce), sce$sid)
dy <- sapply(cs, \(.) diff(range(sce[, .]$CenterX_global_mm)))
names(gs) <- gs <- colnames(ys)

groups <- cut(seq_along(gs), 3)
groups <- split(seq_along(gs), groups)
for (. in seq_along(groups)) {
    pdf(sprintf("figs/sig,xy%s.pdf", .), 9, 6, onefile=TRUE)
    lapply(sort(gs)[groups[[.]]], \(g) { cat(g)
        gg <- lapply(names(cs)[order(dy)], \(id) {
            c <- cs[[id]]
            se <- sce[, c]
            val <- unname(ys[c, g])
            .plt_xy(se, val, s=0.4, id=id, o=FALSE, dpi=300) +
            scale_color_gradientn(g, 
                na.value="white",
                colors=rev(pals::brewer.rdbu(11)),
                limits=c(-2.5, 2.5), breaks=seq(-2, 2, 2))
                #low="turquoise", mid="lavender", high="magenta")
        }) |> wrap_plots(
            nrow=3, guides="collect", 
            heights=rep(1, length(cs)/6)) & 
            theme(
                legend.position="bottom",
                legend.title.position="top",
                legend.key.height=unit(0.4, "lines"),
                legend.key.width=unit(0.8, "lines"))
        print(gg)
    })
    dev.off()
}
```

```{r um2-g2m}
#| code-fold: true
es <- assay(sig)["HM_G2M_CHECKPOINT", ]
df <- data.frame(colData(sig), es)
df <- df |>
    filter(lv2 == "tum") |>
    mutate(es=cut(es, 5)) |>
    mutate(bin=as.integer(es))
(gg <- ggplot(df, aes(es, log2(Area.um2/mean(Area.um2)), fill=factor(bin))) + 
    geom_boxplot(shape=16, linewidth=0.2, key_glyph="point",
        outlier.shape=16, outlier.stroke=0, outlier.size=0.2) +
    scale_fill_manual(NULL, values=hcl.colors(5, "Zissou 1")) +
    #geom_point(shape=16, stroke=0) +
    scale_color_manual(values=.pal_pid) +
    geom_smooth(formula=y~x, method="lm", se=FALSE, linewidth=0.2, col="black") +
    labs(x="HM_G2M_CHECKPOINT", y="cell area (um2) log2-\nfold change to average") +
    .thm_fig_d("bw", "f") + theme(
        aspect.ratio=3/2,
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.minor=element_blank()))
```

```{r include=FALSE}
ggsave("figs/um2_vs_g2m.pdf", gg, units="cm", width=3, height=3)
```

```{r sig-plt, results="hold"}
# order contexts by tumor fraction
xo_ctx <- scale_x_discrete(limits=levels(sce$cty))
xo_bin <- scale_x_discrete(limits=levels(sce$bin))
# order cores by proliferation proxy
idx <- which(sig$lv2 == "tum")
mx <- assay(sig)["HM_G2M_CHECKPOINT", idx]
mu <- by(mx, sig$sid[idx], mean)
(o <- names(sort(mu)))
xo_sid <- scale_x_discrete(limits=o)
```

```{r echo=FALSE}
.plt_cor <- \(se) {
    pal <- rev(pals::brewer.rdbu(99))
    pheatmap::pheatmap(cor(t(assay(se))),
        main="inter-signature correlation",
        cellwidth=6, cellheight=6,
        treeheight_row=12, treeheight_col=12, 
        fontsize=6, color=pal, border_color=NA)
}
.plt_avg <- \(se, by) {
    df <- data.frame(t(assay(se)), colData(se), check.names=FALSE)
    fd <- pivot_longer(df, all_of(rownames(se)))
    mu <- fd |>
        filter(!is.na(!!sym(by))) |>
        group_by(name, !!sym(by)) |>
        summarise_at("value", mean) |>
        group_by(name) |>
        mutate_at("value", .z)
    mx <- pivot_wider(mu)
    my <- as.matrix(mx[, -1])
    rownames(my) <- mx[[1]]
    ggplot(mu, aes(.data[[by]], name, fill=value)) + geom_tile() +
        scale_fill_gradientn(
            "z-scaled\nmean UCell", 
            colors=.pal_sig,
            limits=c(-2.5, 2.5), breaks=seq(-2, 2, 2)) +
        scale_x_discrete(limits=.xo(my)) +
        scale_y_discrete(limits=.yo(my)) +
        coord_equal(expand=FALSE) +
        .thm_fig_c("minimal") + theme(
            axis.title=element_blank(),
            axis.text.y=element_text(size=3),
            axis.text.x=element_text(size=3, angle=90, hjust=1, vjust=0.5))
}
```

```{r echo=FALSE}
gs <- c("HM_G2M_CHECKPOINT", "HM_MYC_TARGETS_V1")
pol <- read_parquet("outs/pol.parquet", as_data_frame=FALSE)
se <- sig[, sig$sid == "111LNn"]
ps <- lapply(gs, \(.) {
ys <- assay(se)[., ]
ys[se$lv2 != "tum"] <- NA
se$. <- .q(ys)
.plt_ps(pol, se, ".", na="seashell", id=.)
})
.pdf(ps, "figs/sig,xy,111LNn.pdf", 10)
```

```{r sig-tum}
.sig <- sig[rowData(sig)$typ != "t-atlas", which(sig$lv2 =="tum")]
```

```{r fig.width=8, fig.height=8}
(hm <- .plt_cor(.sig))
```

```{r include=FALSE}
pdf("figs/sig_cm.pdf", width=7, height=7); print(hm); dev.off()
```

```{r echo=FALSE}
.md <- \(ids) {
    md <- c("sid", "Ki67", "PFS", "LDH", "LDHNORML", "AGE",
        "MCL35", "Morphology", "SOX11.IHC", "MYC.IHC", "SEX", "TREATMENT")
    md <- data.frame(colData(sce))[match(ids, sce$sid), md]
    pal <- list(sid=.pal_sid, pid=.pal_pid, gid=.pal_gid, typ=.pal_typ)
    aes <- list(
        theme_void(6),
        coord_equal(expand=FALSE),
        geom_tile(col="white", alpha=2/3),
        scale_y_discrete(position="right"),
        theme(axis.title.y=element_text(size=3, hjust=0, margin=margin(l=4))))
    ps <- lapply(names(md)[-1], \(.) {
        col <- if (. %in% names(pal)) {
            scale_fill_manual(values=pal[[.]])
        } else if (is.numeric(md[[.]])) {
            md[[.]] <- round(md[[.]], 2)
            scale_fill_gradientn(colors=c("white", "red3"))
        } else scale_fill_manual(values=c("lightblue", "pink", "palegreen"))
        ggplot(md, aes(sid, 0, fill=.data[[.]])) + 
            #geom_text(aes(label=.data[[.]]), size=1) +
            labs(x=NULL, y=.) + aes + col 
    })
    ps[[length(ps)]] <- ps[[length(ps)]] + theme(
        axis.text.x=element_text(angle=90, vjust=0.5, margin=margin(t=4)))
    wrap_plots(ps, 
        ncol=1, guides="collect") &
        theme(legend.position="none") &
        scale_x_discrete(limits=ids) 
}
```

```{r sig-tum-hm, warning=FALSE, fig.width=8, fig.height=4}
#| code-fold: true
p1 <- .plt_avg(.sig, "sid") 
p2 <- .md(p1@scales$scales[[2]]$limits) + theme(axis.text.x=element_blank())
hs <- c(length(unique(p1@data$name)), ncol(p2@data)-1)
(p <- wrap_plots(p1, p2, heights=hs, ncol=1, guides="collect"))
```

```{r echo=FALSE, include=FALSE}
use <- c(
    "Quiescent",
    "SOX11 network",
    "BCR_component",
    "Immediate-early response",
    "BCR signaling/NFKB pathway",
    "HM_TNFA_SIGNALING_VIA_NFKB",
    "HM_TGFB_SIGNALING",
    "HM_NOTCH_SIGNALING",
    "HM_IL2_STAT5_SIGNALING",
    "HM_IL6_JAK_STAT3_SIGNALING",
    "S-Phase",
    "MYC pathway",
    "HM_MYC_TARGETS_V1",
    "HM_MYC_TARGETS_V2",
    "MP_CELL_CYCLE",
    "HM_E2F_TARGETS",
    "HM_G2M_CHECKPOINT")
p1 <- .plt_avg(.sig[use], "sid") + scale_y_discrete(limits=rev(use))
p2 <- .md(p1@scales$scales[[2]]$limits) + theme(axis.text.x=element_blank())
hs <- c(length(unique(p1@data$name)), ncol(p2@data)-1)
(pq <- wrap_plots(p1, p2, heights=hs, ncol=1, guides="collect"))
```

```{r include=FALSE}
ggsave("figs/sig,hm_by_sid.pdf", pq, units="cm", width=8, height=4)
```

## signaling

```{r ccc}
(x <- altExp(sce, "COMMOT"))
```

```{r plt-hm}
#| code-fold: true
.plt_hm <- \(df, gs, x, xo=TRUE, yo=TRUE, ax=TRUE) {
    # wrangling
    mu <- df |>
        group_by(!!!sym(x)) |>
        summarise(across(all_of(gs), mean))
    # scaling
    fd <- mu |>
        mutate(across(all_of(gs), .z)) |>
        pivot_longer(all_of(gs))
    # ordering
    mx <- pivot_wider(fd)
    my <- as.matrix(mx[, -1])
    rownames(my) <- seq(nrow(my))
    xo <- if (xo) scale_x_discrete(limits=mx[[1]][as.integer(.xo(my))])
    yo <- if (yo) scale_y_discrete(limits=.yo(my))
    # aesthetics
    ax <- if (ax) theme(
        #axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.text.y=element_text(size=3),
        axis.text.x=element_text(size=4, angle=45, vjust=1, hjust=1)) else
        theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())
    # plotting
    ggplot(fd, aes(.data[[x]], name, fill=value)) +
        scale_fill_gradientn(
            "z-scaled\nmean score",
            colors=.pal_ccc,
            limits=c(-2.5,2.5), breaks=seq(-2,2,2)) +
        labs(y=NULL) + coord_equal(2/3, expand=FALSE) + 
        geom_tile() + xo + yo + .thm_fig_c("bw") + ax
}
```

### pws

```{r pws}
gs <- rownames(y <- x[rowData(x)$type == "Pathway", ])
mx <- t(as.matrix(Reduce(`+`, assays(y))/2))
df <- data.frame(colData(sce), mx, check.names=FALSE)
```

```{r pws-ctx-joint, fig.width=15, fig.height=8}
#| code-fold: true
mu <- by(mx, df$cty, colMeans)
mv <- as.matrix(array2DF(mu)[, -1])
rownames(mv) <- names(mu)
gs <- lapply(xs <- rownames(mv), \(i) {
    j <- setdiff(xs, i)
    b <- colMeans(mv[j, ])
    names(tail(sort(mv[i, ]/b), 5))
})
gs <- unique(unlist(gs))
(gg <- .plt_hm(df, gs, "cty", xo=FALSE, ax=TRUE) + 
    scale_x_discrete(limits=levels(df$cty)))
```

```{r include=FALSE}
ggsave("figs/pws,hm_by_cty.pdf", gg, units="cm", width=4, height=4.5)
```

```{r pws-ctx-split, fig.width=15, fig.height=8}
#| code-fold: true
mu <- by(mx, df$cty, colMeans)
mv <- as.matrix(array2DF(mu)[, -1])
rownames(mv) <- names(mu)
ps <- lapply(xs <- rownames(mv), \(i) {
    j <- setdiff(xs, i)
    b <- colMeans(mv[j, ])
    gs <- names(tail(sort(mv[i, ]/b), 30))
    .plt_hm(df, gs, "cty", xo=FALSE, ax=TRUE) + ggtitle(i)
})
wrap_plots(ps, nrow=2, guides="collect")
```

### lrs

```{r lrs}
gs <- rownames(y <- x[!rowData(x)$type %in% c("Total", "Pathway"), ])
mx <- t(as.matrix(Reduce(`+`, assays(y))/2))
df <- data.frame(colData(sce), mx, check.names=FALSE)
```

```{r lrs-ctx-joint, fig.width=15, fig.height=8}
#| code-fold: true
mu <- by(mx, df$cty, colMeans)
mv <- as.matrix(array2DF(mu)[, -1])
rownames(mv) <- names(mu)
gs <- lapply(xs <- rownames(mv), \(i) {
    j <- setdiff(xs, i)
    b <- colMeans(mv[j, ])
    names(tail(sort(mv[i, ]/b), 5))
})
gs <- unique(unlist(gs))
(gg <- .plt_hm(df, gs, "cty", xo=FALSE, ax=TRUE))
```

```{r include=FALSE}
ggsave("figs/lrs,hm_by_cty.pdf", units="cm", width=6, height=4.5)
```

```{r lrs-ctx-split, fig.width=15, fig.height=8}
#| code-fold: true
mu <- by(mx, df$cty, colMeans)
mv <- as.matrix(array2DF(mu)[, -1])
rownames(mv) <- names(mu)
ps <- lapply(xs <- rownames(mv), \(i) {
    j <- setdiff(xs, i)
    b <- colMeans(mv[j, ])
    gs <- names(tail(sort(mv[i, ]/b), 30))
    .plt_hm(df, gs, "cty", xo=FALSE, ax=TRUE) + ggtitle(i)
})
wrap_plots(ps, nrow=2, guides="collect")
```

::: {.panel-tabset}

```{r lrs-lv2-split, results="asis", fig.width=15, fig.height=8}
#| code-fold: true
mu <- by(mx, df$lv2, colMeans)
mv <- as.matrix(array2DF(mu)[, -1])
rownames(mv) <- names(mu)
names(xs) <- xs <- rownames(mv)
gs <- lapply(xs, \(i) {
    j <- setdiff(xs, i)
    b <- colMeans(mv[j, ])
    names(tail(sort(mv[i, ]/b), 40))
})
names(ks) <- ks <- sort(levels(df$lv2))
ps <- lapply(ks, \(k) .plt_hm(df, gs[[k]], "lv2", xo=FALSE, ax=TRUE) + ggtitle(k))
for (k in names(ps)) { cat("####", k, "\n"); print(ps[[k]]); cat("\n\n") }
```

:::

```{r include=FALSE}
pdf("figs/lrs,hm_by_lv2.pdf", width=9/2.54, height=6/2.54, onefile=TRUE)
for (k in ks) print(ps[[k]]); dev.off()
```

## appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
#| code-fold: false
sessionInfo()
```

:::
