# ist

## preamble

```{r load-deps, message=FALSE, warning=FALSE}
library(arrow)
library(scran)
library(scuttle)
library(SingleCellExperiment)
source("code/_utils.R")
```

## loading

```{r load-data}
(sce <- readRDS("outs/pro.rds"))
```

## reduction

```{r plt-map, fig.width=6, fig.height=5}
#| code-fold: true
.plt_dr(sce, "pid") + scale_color_manual(values=.pal_pid) +
.plt_dr(sce, "gid") + scale_color_manual(values=.pal_gid) +
.plt_dr(sce, "typ") + scale_color_manual(values=.pal_typ) +
.plt_dr(sce, "lv1") + scale_color_manual(values=.pal_sub) +
    plot_layout(nrow=2) & theme(
        aspect.ratio=1,
        plot.margin=margin(l=5, b=5),
        legend.justification=c(0, 0.5))
```

```{r plt-maq, fig.width=8, fig.height=2.5}
#| code-fold: true
cs <- split(colnames(sce), sce$lv1)
cs <- cs[setdiff(names(cs), "tum")]
ps <- lapply(names(cs), \(.) {
    sub <- sce[, cs[[.]]]
    .plt_dr(sub, "lv2", dr="UMAQ", s=0.4, id=.) +
    scale_color_manual(values=unname(pals::trubetskoy()))
})
wrap_plots(ps, nrow=1) & theme(
    aspect.ratio=1,
    plot.margin=margin(l=5, b=5),
    legend.justification=c(0, 0.5))
```

## marker

```{r mgs, echo=FALSE}
.plt_dp <- \(sce, id, gs) {
    gs <- lapply(gs, intersect, rownames(sce))
    ns <- sapply(gs, length)
    gt <- unlist(gs)
    mu <- summaryMarkerStats(sce[gt, ], sce[[id]])
    mu <- lapply(mu, \(.) data.frame(g=rownames(.), .))
    mu <- mu |>
        bind_rows(.id="k") |>
        group_by(g) |>
        mutate_at("self.average", .z) |>
        mutate_at("g", factor, gt) |>
        mutate_at("k", factor, rev(names(gs)))
    s <- cumsum(ns)
    n <- length(ns)
    bb <- 0.5+data.frame(
        xmin=rev(c(0,s[-n])), xmax=rev(s),
        ymin=seq(n), ymax=c(0,seq(n)[-n]))
    ggplot(mu, aes(g, k, col=self.average, size=self.detected)) + geom_point() +
        geom_rect(inherit.aes=FALSE, fill=NA, col="black", linewidth=0.4,
            aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), bb) +
        scale_color_gradient2(low="blue3", mid="grey95", high="red3") +
        scale_size_continuous(breaks=seq(0, 1, .2), range=c(1, 5)) +
        guides(col=guide_colorbar(order=1)) +
        coord_equal() + 
        .thm_fig_c("minimal") + theme(
            panel.grid=element_blank(),
            axis.title=element_blank(),
            axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
}
```

::: {.panel-tabset}

### nkt

```{r mgs-nkt, fig.width=9, fig.height=3}
gs <- list(
    Tha=c("TRBC1", "TRBC2", "CD2", "CD3D", "CD3E", "CD3G", "STAT4","CD4"),
    Thn=c("CD6"),
    Tcm=c("KLF2", "TUBB2A", "TUBB2B"),
    Tfh=c("ICOS", "BCL6", "CXCL13", "CD40LG"),
    Tcn=c("CD8A", "CD8B", "CCR7", "CD28", "CD44", "CD200A"),
    Treg=c("TNFRSF4", "IL2RA", "FOXP3", "CTLA4"),
    Tex=c("KLRG1", "TIGIT", "HAVCR2", "LAG3", "PDCD1", "VCAM1", 
        "TNFRSF9", "TNFRSF18", "IFNG", "CXCR6", "GLNY", "DUSP4", "TOX"),
    Tp=c("MKI67", "TOP2A", "TUBB4A", "TUBB4B", 
        "CX3CR1", "CDK6", "GZMA", "GZMB", "GZMH", "GZMK", "EOMES"),
    NK=c("ENTPD1", "NKG7", "PRF1", "TBX21", "KLRB1", "KLRC3", "IL2RB", "CD7")
)
sub <- sce[, sce$lv1 == "nkt"]
.plt_dp(sub, "lv2", gs)
```

### mye

```{r mgs-mye, fig.width=9, fig.height=3}
gs <- list(
    AML=c(), 
    DC=c("CLEC9A", "CLEC10A", "LAMP3", "IDO1", "XCR1",
        "HLA-DPA1", "HLA-DPB1", "HLA-DQB1"),
    pDC=c("IRF8", "IRF7", "CR2", "FCRL2", "FCRL5", "CLEC4C"),
    mac.pi=c("CD68", "APOE", "MMP9", "MMP12", "MMP14", "ITGAX"),
    TAM=c("SELENOP", "CD14", "CD163", "C1QA", "C1QB", "C1QC", "CTSB"),
    mono.nc=c("FCER1G", "B2M", "AIF1", "BLVRB"),
    mono.c=c("FBP1", "PCK2", "LYZ")
)
sub <- sce[, sce$lv1 == "mye"]
.plt_dp(sub, "lv2", gs)
```

### str

```{r mgs-str, fig.width=9, fig.height=3}
gs <- list(
    fib=c(
        "COL1A1", "COL1A2", "COL3A1", "COL6A3", "COL5A1", "COL5A2", "COL5A3", 
        "COL14A1", "CXCL10", "ACTA2", "PDGFRA", "PDGFRB", "FN1"),
    mCAF=c("DCN", "COL12A1", "MMP1", "MMP2", "IGF2", "POSTN", "MYL9", "IGFBP5"),
    FRCcts=c("CCN1", "JUNB", "JUN", "FOS", "FOSB", "CCL2", "EGR1", "EGR3", "GBP1"),
    FRCtcz=c("CCL19", "CCL21", "CXCL12", "VCAM1", "COL27A1", "FDCSP", "CLU", "CR2", "CXCL13"),
    FRCpv=c("NOTCH3", "NOTCH4", "COL18A1", "COL4A1", "HEY1", "DLL4", "CAV1", "LAMA4", "LMNA"),
    BEC=c("FLT1", "CLEC14A", "CDH5", "CD34", "CD93", "VWF"),
    LEC=c("MYO6", "SRGN", "LYVE1", "PROX1", "CXCL1", "CXCL2"),
    epi=c("KRT5", "KRT7", "KRT14", "KRT16", "KRT17", "KRT19")
)
sub <- sce[, sce$lv1 == "str"]
.plt_dp(sub, "lv2", gs)
```

:::

## co-loc

```{r bin}
.bin <- \(z, x, a=NULL, nx=10) {
    if (is.matrix(z)) {
        z <- SingleCellExperiment(assays=list(foo=z))
        a <- "foo"
    }
    xs <- cut(.q(x), 
        include.lowest=TRUE,
        breaks=seq(0, 1, l=nx))
    mu <- aggregateAcrossCells(z, ids=xs,
        use.assay.type=a, statistics="mean")
    df <- data.frame(x=mu$ids, t(assay(mu)), check.names=FALSE)
}
```

```{r plt-nns-sig, fig.align="center", fig.width=8, fig.height=3}
#| code-fold: true
# restrict to tumor
sig <- altExp(sce, "UCell")
sel <- rowData(sig)$typ != "t-atlas"
sub <- sig[sel, sig$lv2 == "tum"]
# average by bin
df <- .bin(sub, sub$fqs$tum, assayNames(sub)[1], nx=20)
# scale across bins
fd <- df |>
    pivot_longer(-x) |>
    group_by(name) |>
    mutate_at("value", .z)
# order by peak
yo <- fd |>
    group_by(name) |>
    slice_max(value, with_ties=FALSE) |>
    arrange(x, value) |>
    pull(name) |> rev()
# plotting
ggplot(fd, aes(x, name, fill=value)) +
    geom_tile() + 
    scale_fill_gradientn(
        "z-scaled\nmean score",
        colors=rev(pals::brewer.puor(9)),
        limits=c(-2.5, 2.5), breaks=seq(-2, 2, 2)) +
    labs(x="tumor density", y=NULL) +
    coord_equal(2/3, expand=FALSE) + 
    scale_y_discrete(limits=yo) +
    .thm_fig_c("minimal") + theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r fig.align="center", fig.width=3.5, fig.height=3}
#| code-fold: true
sub <- sce[, sce$lv2 == "tum"]
df <- .bin(t(sub$fqs), sub$fqs$tum, nx=10)
fd <- pivot_longer(df, -1)
fd <- filter(fd, name != "tum")
ggplot(fd, aes(x, value, fill=name)) + 
    geom_col(position="fill", key_glyph="point") +
    scale_fill_manual(NULL, values=.pal_kid) +
    coord_cartesian(expand=FALSE) + 
    .thm_fig_d("minimal", "f") + 
    labs(x="tumor density", y="frequency") +
    theme(aspect.ratio=1, axis.text=element_blank())
```

```{r fig.align="center", fig.width=4, fig.height=2.5}
#| code-fold: true
# binning
sub <- sce[, sce$lv2 == "tum"]
sig <- altExp(sub, "UCell")
es <- c("S-Phase", "G2/M", "MYC pathway")
es <- colSums(assay(sig)[es, ])
fq <- t(as.matrix(sub$fqs))
ex <- fq["tum", ] == 1
df <- .bin(fq[, !ex], es[!ex], nx=20)
# correlation
rho <- cor(
    as.numeric(df[[1]]), 
    as.matrix(df[, -1]))
top <- names(which(abs(rho[1, ]) > 2/3))
rho <- format(rho[1, ], digits=2)
# scaling
fd <- df |>
    pivot_longer(-1) |>
    group_by(name) |>
    mutate_at("value", .z) |>
    filter(name %in% top)
# ordering
yo <- fd |>
    group_by(name) |>
    slice_max(value, with_ties=FALSE) |>
    arrange(x, value) |>
    pull(name) |> rev()
# plottinh
ggplot(fd, aes(x, name, fill=value)) + geom_tile() + 
    annotate("text", nlevels(fd$x)-1, yo, hjust=0.5, size=3, label=rho[yo]) +
    scale_fill_gradientn(
        "z-scaled\nfrequency", 
        colors=rev(pals::brewer.puor(9)),
        limits=c(-2.5, 2.5), breaks=seq(-2, 2, 2)) +
    labs(x="tumor prolif. (mean S + G2/M + MYC)", y=NULL) +
    scale_y_discrete(limits=yo) + coord_equal(2/3, expand=FALSE) + 
    .thm_fig_c("minimal") + theme(
        aspect.ratio=1, 
        panel.grid=element_blank(),
        axis.text.x=element_blank())
```

## appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
#| code-fold: false
sessionInfo()
```

:::
